export const stations = [
	{ name: "Abu Road", code: "ABR" },
	{ name: "Adilabad ", code: "ADB" },
	{ name: "Adoni", code: "AD" },
	{ name: "Adra", code: "ADRA" },
	{ name: "Agartala", code: "AGTL" },
	{ name: "Agra Fort", code: "AF" },
	{ name: "Agra Cantt.", code: "AGC" },
	{ name: "Ahmadnagar", code: "ANG" },
	{ name: "Ahmedabad", code: "ADI" },
	{ name: "Ajmer", code: "AII" },
	{ name: "Ajni", code: "AJNI" },
	{ name: "Akola", code: "AK" },
	{ name: "Aligarh", code: "ALJN" },
	{ name: "Alipurduar Jn.", code: "APDJ" },
	{ name: "Allahabad", code: "ALD" },
	{ name: "Alappuzha", code: "ALLP" },
	{ name: "Alnawar Jn.", code: "LWR" },
	{ name: "Aluva", code: "AWY" },
	{ name: "Alwar", code: "AWR" },
	{ name: "Amalner", code: "AN" },
	{ name: "Amb Andavra", code: "AADR" },
	{ name: "Ambala Cantt.", code: "UMB" },
	{ name: "Ambikapur", code: "ABKP" },
	{ name: "Amla", code: "AMLA" },
	{ name: "Amritsar", code: "ASR" },
	{ name: "Anakapalle", code: "AKP" },
	{ name: "Anand", code: "ANND" },
	{ name: "Anand Nagar", code: "ANDN" },
	{ name: "Anand Vihar Terminus", code: "ANVT" },
	{ name: "Anantapur", code: "ATP" },
	{ name: "Angul", code: "ANGL" },
	{ name: "Annavaram", code: "ANV" },
	{ name: "Anuppur", code: "APR" },
	{ name: "Ara", code: "ARA" },
	{ name: "Arakkonam", code: "AJJ" },
	{ name: "Arsikere", code: "ASK" },
	{ name: "Asansol", code: "ASN" },
	{ name: "Aunrihar", code: "ARJ" },
	{ name: "Aurangabad", code: "AWB" },
	{ name: "Ayodhya", code: "AY" },
	{ name: "Azamgarh", code: "AMH" },
	{ name: "Azimganj Jn.", code: "AZ" },
	{ name: "Badarpur", code: "BPB" },
	{ name: "Badnera Jn.", code: "BD" },
	{ name: "Bagalkot", code: "BGK" },
	{ name: "Baghpat Road", code: "BPM" },
	{ name: "Baidyanathdham", code: "BDME" },
	{ name: "Bakthiyarpur", code: "BKP" },
	{ name: "Balasore", code: "BLS" },
	{ name: "Balaghat", code: "BTC" },
	{ name: "Balangir B", code: "LGR" },
	{ name: "Balugaon", code: "BALU" },
	{ name: "Balurghat", code: "BLGT" },
	{ name: "Balharshah", code: "BPQ" },
	{ name: "Ballia", code: "BUI" },
	{ name: "Banarhat", code: "BNQ" },
	{ name: "Banda Jn.", code: "BNDA" },
	{ name: "Bandel Jn.", code: "BDC" },
	{ name: "Bandikui Jn.", code: "BKI" },
	{ name: "Bandra (T)", code: "BDTS" },
	{ name: "Bangalore City", code: "SBC" },
	{ name: "Bangalore Cantt.", code: "BNC" },
	{ name: "Bangarapet", code: "BWT" },
	{ name: "Bangriposi", code: "BGY" },
	{ name: "Bankura", code: "BQA" },
	{ name: "Banmankhi", code: "BNKI" },
	{ name: "Bapatla", code: "BPP" },
	{ name: "Barabanki Jn.", code: "BBK" },
	{ name: "Barabil", code: "BBN" },
	{ name: "Baran", code: "BAZ" },
	{ name: "Barauni Jn.", code: "BJU" },
	{ name: "Baraut", code: "BTU" },
	{ name: "Barapalli", code: "BRPS" },
	{ name: "Barddhaman Jn.", code: "BWN" },
	{ name: "Bareilly", code: "BE" },
	{ name: "Bargarh Road", code: "BRGA" },
	{ name: "Barhni", code: "BNY" },
	{ name: "Barkakana", code: "BRKA" },
	{ name: "Barmer", code: "BME" },
	{ name: "Barog", code: "BOF" },
	{ name: "Barsoi", code: "BOE" },
	{ name: "Barwadih", code: "BRWD" },
	{ name: "Basar", code: "BSX" },
	{ name: "Basti", code: "BST" },
	{ name: "Bathinda Jn.", code: "BTI" },
	{ name: "Bayana", code: "BXN" },
	{ name: "Beas", code: "BEAS" },
	{ name: "Beawar", code: "BER" },
	{ name: "Belapur", code: "BAP" },
	{ name: "Belgaum", code: "BGM" },
	{ name: "Bellary Jn.", code: "BAY" },
	{ name: "Bettiah", code: "BTH" },
	{ name: "Betul", code: "BZU" },
	{ name: "Bhadohi", code: "BOY" },
	{ name: "Bhadrak", code: "BHC" },
	{ name: "Bhagalpur", code: "BGP" },
	{ name: "Bhagat Ki Kothi", code: "BGKI" },
	{ name: "Bharatpur", code: "BTE" },
	{ name: "Bharuch", code: "BH" },
	{ name: "Bhatapara", code: "BYT" },
	{ name: "Bhatkal", code: "BTJL" },
	{ name: "Bhatni", code: "BTT" },
	{ name: "Bhavnagar (T)", code: "BVC" },
	{ name: "Bhawanipatna", code: "BWPI" },
	{ name: "Bhilwara", code: "BHL" },
	{ name: "Bhimavaram Jn.", code: "BVRM" },
	{ name: "Bhimavaram Town", code: "BVRT" },
	{ name: "Bhind", code: "BIX" },
	{ name: "Bhiwani", code: "BNW" },
	{ name: "Bhopal", code: "BPL" },
	{ name: "Bhubaneswar", code: "BBS" },
	{ name: "Bhuj", code: "BHUJ" },
	{ name: "Bhusaval", code: "BSL" },
	{ name: "Bijapur", code: "BJP" },
	{ name: "Bijnor", code: "BJO" },
	{ name: "Bikaner", code: "BKN" },
	{ name: "Bilaspur Jn.", code: "BSP" },
	{ name: "Bina", code: "BINA" },
	{ name: "Binnaguri", code: "BNV" },
	{ name: "Birur", code: "RRB" },
	{ name: "Bitragunta", code: "BTTR" },
	{ name: "Biyavara Rajgarh", code: "BRRG" },
	{ name: "Bobbili", code: "VBL" },
	{ name: "Boinda B", code: "ONA" },
	{ name: "Barapa Lli", code: "BRPL" },
	{ name: "Baghbahar", code: "BGBR" },
	{ name: "Bokaro Steel City", code: "BKSC" },
	{ name: "Bolpur Shantiniketan", code: "BHP" },
	{ name: "Borivali", code: "BVI" },
	{ name: "Botad", code: "BTD" },
	{ name: "Budaun", code: "BEM" },
	{ name: "Bundi", code: "BUDI" },
	{ name: "Burhanpur", code: "BAU" },
	{ name: "Burhwal", code: "BUW" },
	{ name: "Buxar", code: "BXR" },
	{ name: "Canacona", code: "CNO" },
	{ name: "Chakia", code: "CAA" },
	{ name: "Chakki Bank", code: "CHKB" },
	{ name: "Chakradharpur", code: "CKP" },
	{ name: "Chalisgaon", code: "CSN" },
	{ name: "Champa", code: "CPH" },
	{ name: "Chandausi", code: "CH" },
	{ name: "Chanderiya", code: "CNA" },
	{ name: "Chandigarh", code: "CDG" },
	{ name: "Chandil", code: "CNI" },
	{ name: "Chandrapur", code: "CD" },
	{ name: "Chandrapura", code: "CRP" },
	{ name: "Chaparmukh", code: "CPK" },
	{ name: "Chatrapur", code: "CAP" },
	{ name: "Chengalpattu Jn.", code: "CGL" },
	{ name: "Chengannur", code: "CNGR" },
	{ name: "Chennai Central", code: "MAS" },
	{ name: "Chennai Egmore", code: "MS" },
	{ name: "Chhapra", code: "CPR" },
	{ name: "Chhindwara", code: "CWA" },
	{ name: "Chidambaram", code: "CDM" },
	{ name: "Chikjajur J", code: "JRU" },
	{ name: "Chiplun", code: "CHI" },
	{ name: "Chirala", code: "CLX" },
	{ name: "Chitrakootdham Karvi", code: "CKTD" },
	{ name: "Chittaranjan", code: "CRJ" },
	{ name: "Chittaurgarh", code: "COR" },
	{ name: "Chittoor", code: "CTO" },
	{ name: "Chopan", code: "CPU" },
	{ name: "Chunar", code: "CAR" },
	{ name: "Churu", code: "CUR" },
	{ name: "Coimbatore Jn.", code: "CBE" },
	{ name: "Coonoor", code: "ONR" },
	{ name: "Cuddalore Port", code: "CUPJ" },
	{ name: "Cuddapah", code: "HX" },
	{ name: "Cuttack", code: "CTC" },
	{ name: "Dadar", code: "DR" },
	{ name: "Dahanu Road", code: "DRD" },
	{ name: "Dahod", code: "DHD" },
	{ name: "Dalgaon", code: "DLO" },
	{ name: "Daltonganj", code: "DTO" },
	{ name: "Dallirajhara", code: "DRZ" },
	{ name: "Damoh", code: "DMO" },
	{ name: "Danapur", code: "DNR" },
	{ name: "Darbhanga", code: "DBG" },
	{ name: "Daund", code: "DD" },
	{ name: "Davangere", code: "DVG" },
	{ name: "Dehradun", code: "DDN" },
	{ name: "Dehri-On-Sone", code: "DOS" },
	{ name: "Delhi", code: "DLI" },
	{ name: "New Delhi", code: "NDLS" },
	{ name: "Delhi Cantt.", code: "DEC" },
	{ name: "Delhi Sarai Rohilla", code: "DEE" },
	{ name: "Delhi Shahdara", code: "DSA" },
	{ name: "Deoriasadar", code: "DEOS" },
	{ name: "Devlali", code: "DVL" },
	{ name: "Dhamangaon", code: "DMN" },
	{ name: "Dhanbad", code: "DHN" },
	{ name: "Dharmabad", code: "DAB" },
	{ name: "Dharmanagar", code: "DMR" },
	{ name: "Dharmapuri", code: "DPJ" },
	{ name: "Dharmavaram", code: "DMM" },
	{ name: "Dharwad", code: "DWR" },
	{ name: "Dhasa", code: "DAS" },
	{ name: "Dhaulpur", code: "DHO" },
	{ name: "Dhenuanal", code: "DNUL" },
	{ name: "Dhola", code: "DLJ" },
	{ name: "Dhone", code: "DHNE" },
	{ name: "Dhrangadhra", code: "DHG" },
	{ name: "Dhubri", code: "DBB" },
	{ name: "Dhuri", code: "DUI" },
	{ name: "Dibrugarh", code: "DBRG" },
	{ name: "Dibrugarh Town", code: "DBRT" },
	{ name: "Digha", code: "DGHA" },
	{ name: "Dildarnagar", code: "DLN" },
	{ name: "Dimapur", code: "DMV" },
	{ name: "Dindigul Jn.", code: "DG" },
	{ name: "Dongargarh", code: "DGG" },
	{ name: "Dornakal", code: "DKJ" },
	{ name: "Dungarpur", code: "DNRP" },
	{ name: "Durg", code: "DURG" },
	{ name: "Durgapur", code: "DGR" },
	{ name: "Duvvada", code: "DVD" },
	{ name: "Dwarka", code: "DWK" },
	{ name: "Eluru", code: "EE" },
	{ name: "Ernakulam Jn.", code: "ERS" },
	{ name: "Ernakulam Town", code: "ERN" },
	{ name: "Erode", code: "ED" },
	{ name: "Etawah", code: "ETW" },
	{ name: "Faizabad", code: "FD" },
	{ name: "Faridabad", code: "FDB" },
	{ name: "Farrukhabad", code: "FBD" },
	{ name: "Fatehabad Chand", code: "FTD" },
	{ name: "Fatehpur", code: "FTP" },
	{ name: "Fatuha", code: "FUT" },
	{ name: "Fazilka", code: "FKA" },
	{ name: "Firozabad", code: "FZD" },
	{ name: "Firozpur City", code: "FZP" },
	{ name: "Firozpur Cantt.", code: "FZR" },
	{ name: "Forbesganj", code: "FBG" },
	{ name: "Furkating", code: "FKG" },
	{ name: "Gadag", code: "GDG" },
	{ name: "Gajraula", code: "GJL" },
	{ name: "Gandhidham", code: "GIM" },
	{ name: "Gandhinagar", code: "GADJ" },
	{ name: "Gangapur City", code: "GGC" },
	{ name: "Garwa Road", code: "GHD" },
	{ name: "Gaya", code: "GAYA" },
	{ name: "Gevra Road", code: "GAD" },
	{ name: "Ghatsila", code: "GTS" },
	{ name: "Ghaziabad", code: "GZB" },
	{ name: "Goalpara Town", code: "GLPT" },
	{ name: "Godhra", code: "GDA" },
	{ name: "Gola Gokarannath", code: "GK" },
	{ name: "Gonda", code: "GD" },
	{ name: "Gondia", code: "G" },
	{ name: "Gooty", code: "GY" },
	{ name: "Gorakhpur", code: "GKP" },
	{ name: "Gossaingaon Hat", code: "GOGH" },
	{ name: "Gudivada", code: "GDV" },
	{ name: "Gudur", code: "GDR" },
	{ name: "Gulbarga", code: "GR" },
	{ name: "Guna", code: "GUNA" },
	{ name: "Guntakal", code: "GTL" },
	{ name: "Guntur", code: "GNT" },
	{ name: "Gurgaon", code: "GGN" },
	{ name: "Guruvay Ur", code: "GUV" },
	{ name: "Guwahati", code: "GHY" },
	{ name: "Gwalior", code: "GWL" },
	{ name: "Gyanpur Road", code: "GYN" },
	{ name: "Habibganj", code: "HBJ" },
	{ name: "Hajipur", code: "HJP" },
	{ name: "Haldia", code: "HLZ" },
	{ name: "Haldibari", code: "HDB" },
	{ name: "Hamiltonganj", code: "HOJ" },
	{ name: "Hanumangarh", code: "HMH" },
	{ name: "Hapa", code: "HAPA" },
	{ name: "Hapur", code: "HPU" },
	{ name: "Harda", code: "HD" },
	{ name: "Haridwar", code: "HW" },
	{ name: "Harihar", code: "HRR" },
	{ name: "Harpalpur", code: "HPP" },
	{ name: "Hasimara", code: "HSA" },
	{ name: "Hatia", code: "HTE" },
	{ name: "Hazur Sahib Nanded", code: "NED" },
	{ name: "Hilsa", code: "HIL" },
	{ name: "Himmat Nagar", code: "HMT" },
	{ name: "Hindupur", code: "HUP" },
	{ name: "Hingoli", code: "HNL" },
	{ name: "Hisar", code: "HSR" },
	{ name: "Hoshangabad", code: "HBD" },
	{ name: "Hospet", code: "HPT" },
	{ name: "Hosur", code: "HSRA" },
	{ name: "Howbadh", code: "HBG" },
	{ name: "Howrah", code: "HWH" },
	{ name: "Hubli", code: "UBL" },
	{ name: "Hyderabad", code: "HYB" },
	{ name: "Igatpuri", code: "IGP" },
	{ name: "Indara", code: "IAA" },
	{ name: "Indore", code: "INDB" },
	{ name: "Islampur", code: "IPR" },
	{ name: "Itarsi", code: "ET" },
	{ name: "Jabalpur", code: "JBP" },
	{ name: "Jagdalpur", code: "JDB" },
	{ name: "Jaipur", code: "JP" },
	{ name: "Jaypur", code: "JYP" },
	{ name: "Jaisalmer", code: "JSM" },
	{ name: "Jajpur Keonjhar Road", code: "JJKR" },
	{ name: "Jakhal J", code: "HL" },
	{ name: "Jalamb", code: "JM" },
	{ name: "Jalandhar Cantt. J", code: "JRC" },
	{ name: "Jalandhar City J", code: "JUC" },
	{ name: "Jalgaon", code: "JL" },
	{ name: "Jalna", code: "J" },
	{ name: "Jalpaiguri", code: "JPG" },
	{ name: "Jamalpur", code: "JMP" },
	{ name: "Jammu Tawi", code: "JAT" },
	{ name: "Jamnagar", code: "JAM" },
	{ name: "Janghai", code: "JNH" },
	{ name: "Jasidih", code: "JSME" },
	{ name: "Jaunpur Jn.", code: "JNU" },
	{ name: "Jaynagar", code: "JYG" },
	{ name: "Jetalsar", code: "JLR" },
	{ name: "Jhajha J", code: "AJ" },
	{ name: "Jhansi", code: "JHS" },
	{ name: "Jhargram", code: "JGM" },
	{ name: "Jharsuguda Js", code: "JSG" },
	{ name: "Jind", code: "JIND" },
	{ name: "Jodhpur", code: "JU" },
	{ name: "Jogbani", code: "JBN" },
	{ name: "Jolarpettai", code: "JTJ" },
	{ name: "Jorhat J", code: "T" },
	{ name: "Junagarh Jn. J", code: "JNRD" },
	{ name: "Kacheguda", code: "KCG" },
	{ name: "Kakinada Port", code: "COA" },
	{ name: "Kalchini", code: "KCF" },
	{ name: "Kalka", code: "KLK" },
	{ name: "Kalol", code: "KLL" },
	{ name: "Kalyan", code: "KYN" },
	{ name: "Kamakhya", code: "KYQ" },
	{ name: "Kanchipuram", code: "CJ" },
	{ name: "Kandhla", code: "KQL" },
	{ name: "Kanniyakumari", code: "CAPE" },
	{ name: "Kannur", code: "CAN" },
	{ name: "Kanpur Central", code: "CNB" },
	{ name: "Kanpur Anwarganj", code: "CPA" },
	{ name: "Kaptanganj", code: "CPJ" },
	{ name: "Karaikal", code: "KIK" },
	{ name: "Karaikkudi Jn.", code: "KKDI" },
	{ name: "Karimganj", code: "KXJ" },
	{ name: "Karnal", code: "KUN" },
	{ name: "Karur", code: "KRR" },
	{ name: "Karwar", code: "KAWR" },
	{ name: "Kasaragod", code: "KGQ" },
	{ name: "Kasganj", code: "KSJ" },
	{ name: "Kathgodam", code: "KGM" },
	{ name: "Katihar", code: "KIR" },
	{ name: "Katni", code: "KTE" },
	{ name: "Katni Murwara", code: "KMZ" },
	{ name: "Katpadi", code: "KPD" },
	{ name: "Katwa", code: "KWAE" },
	{ name: "Kazipet", code: "KZJ" },
	{ name: "Kesinga", code: "KSNG" },
	{ name: "Kendujhargarh", code: "KDJR" },
	{ name: "Khagaria", code: "KGG" },
	{ name: "Khalilabad", code: "KLD" },
	{ name: "Khammam", code: "KMT" },
	{ name: "Khandwa", code: "KNW" },
	{ name: "Kharagpur", code: "KGP" },
	{ name: "Khekra", code: "KEX" },
	{ name: "Khurda Road", code: "KUR" },
	{ name: "Khurja", code: "KRJ" },
	{ name: "Kishanganj", code: "KNE" },
	{ name: "Kishangarh", code: "KSG" },
	{ name: "Kiul", code: "KIUL" },
	{ name: "Kochuveli", code: "KCVL" },
	{ name: "Kodaikanal Road", code: "KQN" },
	{ name: "Kolkata", code: "KOAAKO" },
	{ name: "Llam", code: "QLN" },
	{ name: "Kopergaon", code: "KPG" },
	{ name: "Koraput", code: "KRPU" },
	{ name: "Korba", code: "KRBA" },
	{ name: "Kota", code: "KOTA" },
	{ name: "Kotdwara", code: "KTW" },
	{ name: "Kot Kapura", code: "KKP" },
	{ name: "Kottayam", code: "KTYM" },
	{ name: "Kozhikode", code: "CLT" },
	{ name: "Krishnanagar City", code: "KNJ" },
	{ name: "Krishnarajapuram", code: "KJM" },
	{ name: "Kumarghat", code: "KUGT" },
	{ name: "Kumbakonam", code: "KMU" },
	{ name: "Kundapura", code: "KUDA" },
	{ name: "Kurduwadi", code: "KWV" },
	{ name: "Kurnool Town", code: "KRNT" },
	{ name: "Kurukshetra", code: "KKDE" },
	{ name: "Lakhimpur L", code: "MP" },
	{ name: "Laksar", code: "LRJ" },
	{ name: "Lalgarh", code: "LGH" },
	{ name: "Lalgola L", code: "GL" },
	{ name: "Lalitpur", code: "LAR" },
	{ name: "Lalkuan Jn.", code: "LKU" },
	{ name: "Latur", code: "LUR" },
	{ name: "Ledo L", code: "EDO" },
	{ name: "Loharu", code: "LHU" },
	{ name: "Lokmanya Tilak (T) L", code: "TT" },
	{ name: "Lonavla L", code: "NL" },
	{ name: "Londa", code: "LD" },
	{ name: "Lower Halflong L", code: "FG" },
	{ name: "Lucknow", code: "LJN/LKO" },
	{ name: "Ludhiana", code: "LDH" },
	{ name: "Lumding", code: "LMG" },
	{ name: "Luni", code: "LUNI" },
	{ name: "Machilipatnam", code: "MTM" },
	{ name: "Madarihat", code: "MDT" },
	{ name: "Maddur", code: "MAD" },
	{ name: "Madgaon (Goa)", code: "MAO" },
	{ name: "Madhubani", code: "MBI" },
	{ name: "Madhupur", code: "MDP" },
	{ name: "Madurai Jn.", code: "MDU" },
	{ name: "Mahasamund", code: "MSMD" },
	{ name: "Mahbubnagar", code: "MBNR" },
	{ name: "Mahuva", code: "MHV" },
	{ name: "Muniguda", code: "MNGD" },
	{ name: "Mahesana", code: "MSH" },
	{ name: "Mahoba", code: "MBA" },
	{ name: "Mailani ", code: "MLN" },
	{ name: "Maksi ", code: "MKC" },
	{ name: "Malda Town", code: "MLDT" },
	{ name: "Manamadurai ", code: "MNM" },
	{ name: "Manduadih", code: "MUV" },
	{ name: "Mangalore Central", code: "MAQ" },
	{ name: "Mangalore Jn.", code: "MAJN" },
	{ name: "Manikpur", code: "MKP" },
	{ name: "Mankapur", code: "MUR" },
	{ name: "Manmad", code: "MMR" },
	{ name: "Mannargudi", code: "MQ" },
	{ name: "Mansi", code: "MNE" },
	{ name: "Manu", code: "MANU" },
	{ name: "Mariani", code: "MXN" },
	{ name: "Marwar Jn.", code: "MJ" },
	{ name: "Mathura", code: "MTJ" },
	{ name: "Mau", code: "MAU" },
	{ name: "Mayiladuturai Jn.", code: "MV" },
	{ name: "Meerut City", code: "MTC" },
	{ name: "Merta Road", code: "MTD" },
	{ name: "Mettupalayam", code: "MTP" },
	{ name: "Midnapore", code: "MDN" },
	{ name: "Miraj", code: "MRJ" },
	{ name: "Miryalaguda", code: "MRGA" },
	{ name: "Mirzapur", code: "MZP" },
	{ name: "Moga", code: "MOF" },
	{ name: "Mokama", code: "MKA" },
	{ name: "Pudukottai", code: "PDKT" },
	{ name: "Pulgaon", code: "PLO" },
	{ name: "Pune Jn.", code: "PUNE" },
	{ name: "Puranpur", code: "PP" },
	{ name: "Puri", code: "PURI" },
	{ name: "Purna", code: "PAU" },
	{ name: "Purnia", code: "PRNA" },
	{ name: "Purulia", code: "PRR" },
	{ name: "Radhikapur", code: "RDP" },
	{ name: "Rae Bareli", code: "RBL" },
	{ name: "Raichur", code: "RC" },
	{ name: "Raigarh", code: "RIG" },
	{ name: "Raipur", code: "R" },
	{ name: "Rajahmundry", code: "RJY" },
	{ name: "Raja-Ka-Sahaspur", code: "RJK" },
	{ name: "Raja-Ki-Mandi", code: "RKM" },
	{ name: "Rajendranagar", code: "RJQ" },
	{ name: "Rajgir", code: "RGD" },
	{ name: "Rajkot", code: "RJT" },
	{ name: "Rajnandgaon", code: "RJN" },
	{ name: "Rajpura", code: "RPJ" },
	{ name: "Ramagundam", code: "RDM" },
	{ name: "Ramanathapuram", code: "RMD" },
	{ name: "Rameswaram", code: "RMM" },
	{ name: "Ramnagar", code: "RMR" },
	{ name: "Rampur Jn.", code: "RMU" },
	{ name: "Rampurhat", code: "RPH" },
	{ name: "Ranaghat", code: "RHA" },
	{ name: "Ranchi", code: "RNC" },
	{ name: "Rangapara North", code: "RPAN" },
	{ name: "Rangiya", code: "RNY" },
	{ name: "Raninagar", code: "ROJ" },
	{ name: "Ratangarh", code: "RTGH" },
	{ name: "Ratlam", code: "RTM" },
	{ name: "Ratnagiri ", code: "RN" },
	{ name: "Rawatganj ", code: "RJ" },
	{ name: "Raxaul", code: "RXL" },
	{ name: "Rayagada", code: "RGDA" },
	{ name: "Renigunta", code: "RU" },
	{ name: "Rewa", code: "REWA" },
	{ name: "Rewari ", code: "RE" },
	{ name: "Ringus", code: "RGS" },
	{ name: "Rohtak", code: "ROK" },
	{ name: "Roorkee", code: "RK" },
	{ name: "Rourkela", code: "ROU" },
	{ name: "Sadulpur", code: "SDLP" },
	{ name: "Sagar Jambagaru S", code: "RF" },
	{ name: "Sagauli ", code: "SGL" },
	{ name: "Sagour S", code: "GO" },
	{ name: "Saharanpur S", code: "SRE" },
	{ name: "Saharsa", code: "SHC" },
	{ name: "Sahibganj ", code: "SBG" },
	{ name: "Sai Nagar Shirdi ", code: "SNSI" },
	{ name: "Salem", code: "SA" },
	{ name: "Salempur S", code: "SRU" },
	{ name: "Samalkot Sl", code: "O" },
	{ name: "Samastipur", code: "SPJ" },
	{ name: "Sambalpur", code: "SBP" },
	{ name: "Sambalpur City", code: "SBPY" },
	{ name: "Samdari ", code: "SMR" },
	{ name: "Samuktala Road", code: "AMTA" },
	{ name: "Sangli", code: "SLI" },
	{ name: "Santragachi", code: "SRC" },
	{ name: "Sarnath", code: "SRNT" },
	{ name: "Satara", code: "STR" },
	{ name: "Satna", code: "STA" },
	{ name: "Sattenapalle", code: "SAP" },
	{ name: "Sawaimadhopur", code: "SWM" },
	{ name: "Sawantwadi Road S", code: "WV" },
	{ name: "Sealdah", code: "SDAH" },
	{ name: "Secunderabad", code: "SC" },
	{ name: "Sengottai ", code: "SCT" },
	{ name: "Sensoa", code: "SCF" },
	{ name: "Sewagram", code: "SEGM" },
	{ name: "Shahabad", code: "SDB" },
	{ name: "Shahganj ", code: "SHG" },
	{ name: "Shahjahanpur S", code: "SZP" },
	{ name: "Shahpur Patoree", code: "SPP" },
	{ name: "Shaktinagar", code: "SKTN" },
	{ name: "Shalimar", code: "SHM" },
	{ name: "Shamgarh", code: "SGZ" },
	{ name: "Shamli", code: "SMQL" },
	{ name: "Shikohabad", code: "SKB" },
	{ name: "Shimla", code: "SML" },
	{ name: "Shimoga Town S", code: "MET" },
	{ name: "Shivpuri", code: "SVPI" },
	{ name: "Shoranur Jn. S", code: "RR" },
	{ name: "Shri Mahabirji S", code: "MBJ" },
	{ name: "Sihor Gujarat S", code: "OJN" },
	{ name: "Sikar", code: "SIKR" },
	{ name: "Moradabad", code: "MB" },
	{ name: "Motihari", code: "MKI" },
	{ name: "Mudkhed", code: "MUE" },
	{ name: "Mughalsarai", code: "MGS" },
	{ name: "Mumbai Central", code: "BCT" },
	{ name: "Mumbai Cst", code: "CSTM" },
	{ name: "Muri ", code: "MURI" },
	{ name: "Murkeongselek", code: "MZS" },
	{ name: "Murtajapur", code: "MZR" },
	{ name: "Muzaffar Nagar", code: "MOZ" },
	{ name: "Muzaffarpur", code: "MFP" },
	{ name: "Mysore", code: "MYS" },
	{ name: "Nabadwipdham ", code: "NDAE" },
	{ name: "Nadiad", code: "ND" },
	{ name: "Nadikudi", code: "NDKD" },
	{ name: "Nagappatt Inam", code: "NGT" },
	{ name: "Nagarkata", code: "NKB" },
	{ name: "Nagarsol ", code: "NSL" },
	{ name: "Nagbhir", code: "NAB" },
	{ name: "Nagda", code: "NAD" },
	{ name: "Nagercoil Jn.", code: "NCJ" },
	{ name: "Nagore", code: "NCR" },
	{ name: "Nagpur", code: "NGP" },
	{ name: "Nainpur", code: "NIR" },
	{ name: "Najibabad", code: "NBD" },
	{ name: "Nalanda", code: "NLD" },
	{ name: "Nalgonda", code: "NLDA" },
	{ name: "Namakkal", code: "NMKL" },
	{ name: "Nandalur", code: "NRE" },
	{ name: "Nandgaon", code: "NGN" },
	{ name: "Nandurbar", code: "NDB" },
	{ name: "Nandyal", code: "NDL" },
	{ name: "Nangal Dam", code: "NLDM" },
	{ name: "Narkatiaganj", code: "NKE" },
	{ name: "Narasapur", code: "NS" },
	{ name: "Narsingpur", code: "NU" },
	{ name: "Narwana", code: "NRW" },
	{ name: "Nasik Road", code: "NK" },
	{ name: "Naugarh", code: "NUH" },
	{ name: "Nellore", code: "NLR" },
	{ name: "Neta Ji", code: "SUBHASH" },
	{ name: "Chandra Bose Gomoh", code: "GMO" },
	{ name: "New Alipurduar", code: "NOQ" },
	{ name: "New Bongaigaon", code: "NBQ" },
	{ name: "New Coochbehar", code: "NCB" },
	{ name: "New Farakka", code: "NFK" },
	{ name: "New Jalpaiguri", code: "NJP" },
	{ name: "Newmal Jn.", code: "NMZ" },
	{ name: "New Tinsukia", code: "NTSK" },
	{ name: "Nidadavolu", code: "NDD" },
	{ name: "Nidamangalam", code: "NMJ" },
	{ name: "Nidubrolu", code: "NDO" },
	{ name: "Nimach", code: "NMH" },
	{ name: "Nizamabad", code: "NZB" },
	{ name: "Nizamuddin", code: "NZM" },
	{ name: "Noli", code: "NOLI" },
	{ name: "North Lakhimpur", code: "NLP" },
	{ name: "Odlabari", code: "ODB" },
	{ name: "Okha", code: "OKHA" },
	{ name: "Ongole", code: "OGL" },
	{ name: "Orai", code: "ORAI" },
	{ name: "Pachora", code: "PC" },
	{ name: "Palani", code: "PLNI" },
	{ name: "Palanpur", code: "PNU" },
	{ name: "Palasa", code: "PSA" },
	{ name: "Palakkad", code: "PGT" },
	{ name: "Palakkad Town", code: "PGTN" },
	{ name: "Paliakalan", code: "PLK" },
	{ name: "Pandharapur", code: "PVR" },
	{ name: "Panipat", code: "PNP" },
	{ name: "Paradeep", code: "PRDP" },
	{ name: "Parasnath", code: "PNME" },
	{ name: "Panvel", code: "PNVL" },
	{ name: "Parbhani", code: "PBN" },
	{ name: "Parvatipuram Town", code: "PVPT" },
	{ name: "Pathankot", code: "PTK" },
	{ name: "Patiala", code: "PTA" },
	{ name: "Patna", code: "PNBE" },
	{ name: "Patna Sahib", code: "PNC" },
	{ name: "Phalodi", code: "PLC" },
	{ name: "Phaphamau", code: "PFM" },
	{ name: "Phulera", code: "FL" },
	{ name: "Pilibhit", code: "PBE" },
	{ name: "Pipariya", code: "PPI" },
	{ name: "Podanur", code: "PTJ" },
	{ name: "Porbandar", code: "PBR" },
	{ name: "Pratapgarh", code: "PBH" },
	{ name: "Puducherry", code: "PDY" },
	{ name: "Silchar S", code: "CL" },
	{ name: "Silghat S", code: "HTT" },
	{ name: "Siliguri", code: "SGUJ" },
	{ name: "Siliguri Town S", code: "GUT" },
	{ name: "Simaluguri", code: "SLGR" },
	{ name: "Singrauli", code: "SGRL" },
	{ name: "Sirpur Kagaznagar S", code: "KZR" },
	{ name: "Sirsa", code: "SSA" },
	{ name: "Siswa Bazar S", code: "BZ" },
	{ name: "Sitamarhi S", code: "MI" },
	{ name: "Sitapur City S", code: "SPC" },
	{ name: "Sitapur Cantt. S", code: "CC" },
	{ name: "Siuri", code: "SURI" },
	{ name: "Siwan", code: "SV" },
	{ name: "Sojat Road S", code: "OD" },
	{ name: "Solan", code: "SOL" },
	{ name: "Solapur", code: "SUR" },
	{ name: "Somnath S", code: "MNH" },
	{ name: "Sompeta", code: "SPT" },
	{ name: "Sonpur", code: "SEE" },
	{ name: "Sri", code: "CHHATRAPATI" },
	{ name: "Shahu Maharaj (T)", code: "CSMT" },
	{ name: "Sri Dungargarh S", code: "DGH" },
	{ name: "Sriganga Nagar", code: "SGNR" },
	{ name: "Srikakulam Road", code: "CHE" },
	{ name: "Sri Sathyasai", code: "PRASHANTI" },
	{ name: "Nilayam Ss", code: "SSPN" },
	{ name: "Sujangarh", code: "SUJH" },
	{ name: "Sultanpur Sl", code: "N" },
	{ name: "Surat", code: "ST" },
	{ name: "Suratgarh", code: "SOG" },
	{ name: "Surathkal S", code: "L" },
	{ name: "Surendra Nagar", code: "SUNR" },
	{ name: "Tadepalligudem", code: "TDD" },
	{ name: "Tambaram", code: "TBM" },
	{ name: "Tatanagar", code: "TATA" },
	{ name: "Thalassery", code: "TLY" },
	{ name: "Tenali", code: "TEL" },
	{ name: "Tenkasi", code: "TS" },
	{ name: "Tezpur", code: "TZTB" },
	{ name: "Thanjavur", code: "TJ" },
	{ name: "Thiruvarur.", code: "TVR" },
	{ name: "Tiruchchirappalli Jn.", code: "TPJ" },
	{ name: "Tiruchendur", code: "TCN" },
	{ name: "Tirunelveli", code: "TEN" },
	{ name: "Tirupati", code: "TPTY" },
	{ name: "Tiruppur", code: "TUP" },
	{ name: "Tirur", code: "TIR" },
	{ name: "Titlagarh", code: "TIG" },
	{ name: "Thrisur", code: "TCR" },
	{ name: "Thiruvananthapuram", code: "TVC" },
	{ name: "Tiruvannama Lai", code: "TNM" },
	{ name: "Tumsar Road", code: "TMR" },
	{ name: "Tundla", code: "TDL" },
	{ name: "Tuni", code: "TUNI" },
	{ name: "Tuticorin", code: "TN" },
	{ name: "Udaipur City", code: "UDZ" },
	{ name: "Udhampur", code: "UHP" },
	{ name: "Udhna", code: "UDN" },
	{ name: "Udupi", code: "UD" },
	{ name: "Ujjain", code: "UJN" },
	{ name: "Una", code: "UNA" },
	{ name: "Unchahar", code: "UCR" },
	{ name: "Unnao", code: "ON" },
	{ name: "Vadakara", code: "BDJ" },
	{ name: "Vadodara", code: "BRC" },
	{ name: "Valsad", code: "BL" },
	{ name: "Vanchi Maniyachchi Jn.", code: "MEJ" },
	{ name: "Varanasi", code: "BSB" },
	{ name: "Varkala", code: "VAK" },
	{ name: "Vasai Road", code: "BSR" },
	{ name: "Vasco-Da-Gama", code: "VSG" },
	{ name: "Velankanni", code: "VLKN" },
	{ name: "Veraval", code: "VRL" },
	{ name: "Vidisha", code: "BHS" },
	{ name: "Vijayawada", code: "BZA" },
	{ name: "Villupuram Jn.", code: "VM" },
	{ name: "Viramgam", code: "VG" },
	{ name: "Virudunagar Jn.", code: "VPT" },
	{ name: "Visakhapatnam", code: "VSKP" },
	{ name: "Vizianagaram", code: "VZM" },
	{ name: "Vriddhachalam Jn.", code: "VRI" },
	{ name: "Wadi", code: "WADI" },
	{ name: "Wankaner", code: "WKR" },
	{ name: "Warangal ", code: "WL" },
	{ name: "Wardha Jn.", code: "WR" },
	{ name: "Yesvantpur", code: "YPR" },
	{ name: "Zafarabad", code: "ZBD" },
];
